---
- name: Set selinux policy and mode
  selinux:
    policy: "{{ selinux_policy }}"
    state: "{{ selinux_mode }}"
  register: selinux_result

- debug:
    var: selinux_result

- name: Reboot if required
  reboot:
  when: selinux_reboot | bool and selinux_result.reboot_required
