---
- name: Converge
  hosts: all
  vars:
    etc_hosts_custom_hosts:
      "10.0.0.1":
        - myhost
        - myhost.example.com
      "fc00::1":
        - myv6host
        - myv6host.example.com
  tasks:
    - name: "Include ansible-role-etc-hosts"
      include_role:
        name: "ansible-role-etc-hosts"
